name: .NET Build with SonarQube

on:
  push:
    branches:
      - master
      - main

  pull_request:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Restore dependencies
        run: dotnet restore GithubActionTest.sln

      - name: Build
        run: dotnet build GithubActionTest.sln --no-restore

      - name: Run SonarQube Analysis
        run: |
          dotnet sonarscanner begin \
            /k:"SuryaTejasHP_GithubActionTest" \
            /o:"${{ secrets.SONAR_ORGANIZATION }}" \
            /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
            /d:sonar.cs.vscoveragexml.reportsPaths=**/coverage.cobertura.xml

      - name: Build (for SonarQube)
        run: dotnet build GithubActionTest.sln --no-restore

      - name: Run Unit Tests with Coverage
        run: |
          dotnet test GithubActionUnitTest/GithubActionUnitTest.csproj \
            --no-build \
            --collect:"XPlat Code Coverage" \
            --results-directory TestResults \
            /p:CollectCoverage=true \
            /p:CoverletOutput=TestResults/coverage.cobertura.xml \
            /p:CoverletOutputFormat=cobertura

      - name: End SonarQube Analysis
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"